version: '3.8'
services:
  app:
    build: ./
    container_name: app
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - SERVER_PORT
      - POSTGRESQL_URL
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  postgresql:
    image: bitnami/postgresql:${POSTGRESQL_IMAGE_TAG}
    container_name: postgresql
    restart: ${RESTART_POLICY}
    environment:
      - TZ
      - POSTGRESQL_LOG_TIMEZONE
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE
      - POSTGRESQL_POSTGRES_PASSWORD
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - 5432:5432
volumes:
  postgresql_data:
    driver: local
    name: postgresql_data